// models/User.ts
export interface User {
    id?: string; // UUID (optional because it's generated by the backend)
    name: string;
    email: string;
    password: string;
    role: string; // e.g., "admin", "customer"
}